# Generated by Django 4.1.2 on 2022-10-12 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Event Title"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Event Synopsis"
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Day of Event",
                    ),
                ),
                (
                    "time",
                    models.TimeField(blank=True, null=True, verbose_name="Event Time"),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "EventSchedule_Table",
            },
        ),
    ]
