# Generated by Django 4.1.2 on 2022-10-18 20:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_speaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventschedule",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=app.models.upload_to,
                verbose_name="Speaker Picture",
            ),
        ),
    ]
